alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: openbattleapps
region: nyc
services:
- build_command: |2+

  environment_slug: python
  github:
    branch: main
    repo: stardustsuperwizard/openbattleapps
  health_check:
    http_path: /
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: openbattleapps
  routes:
  - path: /
  run_command: gunicorn wsgi:app --worker-tmp-dir /dev/shm --bind 0.0.0.0:8080 --log-level=debug
    --workers=3
  source_dir: /